
extends:
  - "eslint:recommended"
  - "jquery"
  - "plugin:prettier/recommended"

# jQuery's JSHint recommendations:
# boss: true
# curly: true
# eqeqeq: true
# eqnull: true
# expr: true
# immed: true
# noarg: true
# quotmark: double
# smarttabs: true
# trailing: true
# undef: true
# unused: true

# Accept `window`, etc.
env:
  browser: true

# Known globals (`false`: read-only)
globals:
  define: false
  require: false
  module: false
  jQuery: false

# Custom rules (see https://eslint.org/docs/rules/ )
# 0:off, 1:warn, 2:error
rules:
  no-bitwise: 2
  no-empty:
    - 2
    - {allowEmptyCatch: true}
#   camelcase: 2
#   curly: 2
#   eqeqeq: 2
#   no-unused-expressions: 2
#   wrap-iife:
#     - 2
#     - any
#   no-use-before-define:
#     - 2
#     - functions: false
#   new-cap: 2
#   no-caller: 2
#   no-new: 2
#   no-undef: 2
  one-var:
    - warn
    - always
  no-constant-condition:
    - error
    - { "checkLoops": false }
  no-nested-ternary: 1
  no-unused-vars:
    - 2
    # Allow unused vars in catch() and if start with '_'
    - {args: none, caughtErrors: none, varsIgnorePattern: "^_" }
#   no-cond-assign:
#     - 2
#     - except-parens
  # no-eq-null: 2
  no-eval: 0
